networks:
  board_net:
    driver: bridge

volumes:
  board_redis_data:
    driver: local

services:
  board_service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: board_service
    ports:
      - "${PORT}:8090"
    networks:
      - board_net
    depends_on:
      board_redis:
        condition: service_healthy
    environment:
      REDIS_HOST: board_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      KAFKA_BROKERS: "${KAFKA_BROKERS}"
      OTEL_ADDR: ${OTEL_ADDR}
      PORT: ${PORT}
    restart: unless-stopped

  board_redis:
    image: redis:7.4-alpine
    container_name: board_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - board_redis_data:/data
    networks:
      - board_net
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5