// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/board.proto

package board_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Methodology   string                 `protobuf:"bytes,3,opt,name=methodology,proto3" json:"methodology,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_api_proto_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoardRequest) GetMethodology() string {
	if x != nil {
		return x.Methodology
	}
	return ""
}

func (x *CreateBoardRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type BoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Methodology   string                 `protobuf:"bytes,4,opt,name=methodology,proto3" json:"methodology,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardResponse) Reset() {
	*x = BoardResponse{}
	mi := &file_api_proto_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardResponse) ProtoMessage() {}

func (x *BoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardResponse.ProtoReflect.Descriptor instead.
func (*BoardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardResponse) GetMethodology() string {
	if x != nil {
		return x.Methodology
	}
	return ""
}

func (x *BoardResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsRequest) Reset() {
	*x = GetBoardsRequest{}
	mi := &file_api_proto_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsRequest) ProtoMessage() {}

func (x *GetBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{2}
}

type GetBoardInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardInfoRequest) Reset() {
	*x = GetBoardInfoRequest{}
	mi := &file_api_proto_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardInfoRequest) ProtoMessage() {}

func (x *GetBoardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBoardInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardInfoRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	InCalendar    bool                   `protobuf:"varint,5,opt,name=in_calendar,json=inCalendar,proto3" json:"in_calendar,omitempty"`
	ColumnId      string                 `protobuf:"bytes,6,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_api_proto_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskInfo) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *TaskInfo) GetInCalendar() bool {
	if x != nil {
		return x.InCalendar
	}
	return false
}

func (x *TaskInfo) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type ColumnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BoardId       string                 `protobuf:"bytes,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,4,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Tasks         []*TaskInfo            `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_api_proto_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{5}
}

func (x *ColumnInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnInfo) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ColumnInfo) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *ColumnInfo) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type BoardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Methodology   string                 `protobuf:"bytes,4,opt,name=methodology,proto3" json:"methodology,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Columns       []*ColumnInfo          `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardInfo) Reset() {
	*x = BoardInfo{}
	mi := &file_api_proto_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardInfo) ProtoMessage() {}

func (x *BoardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardInfo.ProtoReflect.Descriptor instead.
func (*BoardInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{6}
}

func (x *BoardInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardInfo) GetMethodology() string {
	if x != nil {
		return x.Methodology
	}
	return ""
}

func (x *BoardInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BoardInfo) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

type GetBoardInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *BoardInfo             `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardInfoResponse) Reset() {
	*x = GetBoardInfoResponse{}
	mi := &file_api_proto_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardInfoResponse) ProtoMessage() {}

func (x *GetBoardInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBoardInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{7}
}

func (x *GetBoardInfoResponse) GetBoard() *BoardInfo {
	if x != nil {
		return x.Board
	}
	return nil
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_api_proto_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBoardRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateBoardRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateBoardRequest) GetCategory() *wrapperspb.StringValue {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_api_proto_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColumnRequest) Reset() {
	*x = CreateColumnRequest{}
	mi := &file_api_proto_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColumnRequest) ProtoMessage() {}

func (x *CreateColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColumnRequest.ProtoReflect.Descriptor instead.
func (*CreateColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{10}
}

func (x *CreateColumnRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColumnRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type ColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BoardId       string                 `protobuf:"bytes,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,4,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnResponse) Reset() {
	*x = ColumnResponse{}
	mi := &file_api_proto_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnResponse) ProtoMessage() {}

func (x *ColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnResponse.ProtoReflect.Descriptor instead.
func (*ColumnResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{11}
}

func (x *ColumnResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnResponse) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ColumnResponse) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type DeleteColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColumnRequest) Reset() {
	*x = DeleteColumnRequest{}
	mi := &file_api_proto_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColumnRequest) ProtoMessage() {}

func (x *DeleteColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColumnRequest.ProtoReflect.Descriptor instead.
func (*DeleteColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteColumnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateColumnRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColumnRequest) Reset() {
	*x = UpdateColumnRequest{}
	mi := &file_api_proto_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColumnRequest) ProtoMessage() {}

func (x *UpdateColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColumnRequest.ProtoReflect.Descriptor instead.
func (*UpdateColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateColumnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateColumnRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	InCalendar    bool                   `protobuf:"varint,4,opt,name=in_calendar,json=inCalendar,proto3" json:"in_calendar,omitempty"`
	ColumnId      string                 `protobuf:"bytes,5,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_proto_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateTaskRequest) GetInCalendar() bool {
	if x != nil {
		return x.InCalendar
	}
	return false
}

func (x *CreateTaskRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	InCalendar    bool                   `protobuf:"varint,5,opt,name=in_calendar,json=inCalendar,proto3" json:"in_calendar,omitempty"`
	ColumnId      string                 `protobuf:"bytes,6,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_proto_board_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{15}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *TaskResponse) GetInCalendar() bool {
	if x != nil {
		return x.InCalendar
	}
	return false
}

func (x *TaskResponse) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type MoveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NewColumnId   string                 `protobuf:"bytes,2,opt,name=new_column_id,json=newColumnId,proto3" json:"new_column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTaskRequest) Reset() {
	*x = MoveTaskRequest{}
	mi := &file_api_proto_board_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTaskRequest) ProtoMessage() {}

func (x *MoveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTaskRequest.ProtoReflect.Descriptor instead.
func (*MoveTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{16}
}

func (x *MoveTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MoveTaskRequest) GetNewColumnId() string {
	if x != nil {
		return x.NewColumnId
	}
	return ""
}

type MoveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NewColumnId   string                 `protobuf:"bytes,2,opt,name=new_column_id,json=newColumnId,proto3" json:"new_column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTaskResponse) Reset() {
	*x = MoveTaskResponse{}
	mi := &file_api_proto_board_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTaskResponse) ProtoMessage() {}

func (x *MoveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTaskResponse.ProtoReflect.Descriptor instead.
func (*MoveTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{17}
}

func (x *MoveTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MoveTaskResponse) GetNewColumnId() string {
	if x != nil {
		return x.NewColumnId
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_proto_board_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateTaskRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_proto_board_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_board_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_board_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_board_proto protoreflect.FileDescriptor

const file_api_proto_board_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/board.proto\x12\x05board\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\x12CreateBoardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vmethodology\x18\x03 \x01(\tR\vmethodology\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\x93\x01\n" +
	"\rBoardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vmethodology\x18\x04 \x01(\tR\vmethodology\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\x12\n" +
	"\x10GetBoardsRequest\"0\n" +
	"\x13GetBoardInfoRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\"\xaa\x01\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vin_calendar\x18\x05 \x01(\bR\n" +
	"inCalendar\x12\x1b\n" +
	"\tcolumn_id\x18\x06 \x01(\tR\bcolumnId\"\x95\x01\n" +
	"\n" +
	"ColumnInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\tR\aboardId\x12!\n" +
	"\forder_number\x18\x04 \x01(\x03R\vorderNumber\x12%\n" +
	"\x05tasks\x18\x05 \x03(\v2\x0f.board.TaskInfoR\x05tasks\"\xbc\x01\n" +
	"\tBoardInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vmethodology\x18\x04 \x01(\tR\vmethodology\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12+\n" +
	"\acolumns\x18\x06 \x03(\v2\x11.board.ColumnInfoR\acolumns\">\n" +
	"\x14GetBoardInfoResponse\x12&\n" +
	"\x05board\x18\x01 \x01(\v2\x10.board.BoardInfoR\x05board\"\x85\x02\n" +
	"\x12UpdateBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x04name\x88\x01\x01\x12C\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\vdescription\x88\x01\x01\x12=\n" +
	"\bcategory\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueH\x02R\bcategory\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_category\"$\n" +
	"\x12DeleteBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13CreateColumnRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\"r\n" +
	"\x0eColumnResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\tR\aboardId\x12!\n" +
	"\forder_number\x18\x04 \x01(\x03R\vorderNumber\"%\n" +
	"\x13DeleteColumnRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x13UpdateColumnRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\xa3\x01\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vin_calendar\x18\x04 \x01(\bR\n" +
	"inCalendar\x12\x1b\n" +
	"\tcolumn_id\x18\x05 \x01(\tR\bcolumnId\"\xae\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vin_calendar\x18\x05 \x01(\bR\n" +
	"inCalendar\x12\x1b\n" +
	"\tcolumn_id\x18\x06 \x01(\tR\bcolumnId\"N\n" +
	"\x0fMoveTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\"\n" +
	"\rnew_column_id\x18\x02 \x01(\tR\vnewColumnId\"O\n" +
	"\x10MoveTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\"\n" +
	"\rnew_column_id\x18\x02 \x01(\tR\vnewColumnId\"\xb8\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x04name\x88\x01\x01\x12C\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xae\x06\n" +
	"\fBoardService\x12@\n" +
	"\vCreateBoard\x12\x19.board.CreateBoardRequest\x1a\x14.board.BoardResponse\"\x00\x12<\n" +
	"\tGetBoards\x12\x17.board.GetBoardsRequest\x1a\x14.board.BoardResponse\"\x00\x12I\n" +
	"\fGetBoardInfo\x12\x1a.board.GetBoardInfoRequest\x1a\x1b.board.GetBoardInfoResponse\"\x00\x12@\n" +
	"\vUpdateBoard\x12\x19.board.UpdateBoardRequest\x1a\x14.board.BoardResponse\"\x00\x12B\n" +
	"\vDeleteBoard\x12\x19.board.DeleteBoardRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\fCreateColumn\x12\x1a.board.CreateColumnRequest\x1a\x15.board.ColumnResponse\"\x00\x12C\n" +
	"\fUpdateColumn\x12\x1a.board.UpdateColumnRequest\x1a\x15.board.ColumnResponse\"\x00\x12D\n" +
	"\fDeleteColumn\x12\x1a.board.DeleteColumnRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\n" +
	"CreateTask\x12\x18.board.CreateTaskRequest\x1a\x13.board.TaskResponse\"\x00\x12=\n" +
	"\bMoveTask\x12\x16.board.MoveTaskRequest\x1a\x17.board.MoveTaskResponse\"\x00\x12=\n" +
	"\n" +
	"UpdateTask\x12\x18.board.UpdateTaskRequest\x1a\x13.board.TaskResponse\"\x00\x12@\n" +
	"\n" +
	"DeleteTask\x12\x18.board.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"\x00B\"Z board_service/pkg/board;board_v1b\x06proto3"

var (
	file_api_proto_board_proto_rawDescOnce sync.Once
	file_api_proto_board_proto_rawDescData []byte
)

func file_api_proto_board_proto_rawDescGZIP() []byte {
	file_api_proto_board_proto_rawDescOnce.Do(func() {
		file_api_proto_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_board_proto_rawDesc), len(file_api_proto_board_proto_rawDesc)))
	})
	return file_api_proto_board_proto_rawDescData
}

var file_api_proto_board_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_board_proto_goTypes = []any{
	(*CreateBoardRequest)(nil),     // 0: board.CreateBoardRequest
	(*BoardResponse)(nil),          // 1: board.BoardResponse
	(*GetBoardsRequest)(nil),       // 2: board.GetBoardsRequest
	(*GetBoardInfoRequest)(nil),    // 3: board.GetBoardInfoRequest
	(*TaskInfo)(nil),               // 4: board.TaskInfo
	(*ColumnInfo)(nil),             // 5: board.ColumnInfo
	(*BoardInfo)(nil),              // 6: board.BoardInfo
	(*GetBoardInfoResponse)(nil),   // 7: board.GetBoardInfoResponse
	(*UpdateBoardRequest)(nil),     // 8: board.UpdateBoardRequest
	(*DeleteBoardRequest)(nil),     // 9: board.DeleteBoardRequest
	(*CreateColumnRequest)(nil),    // 10: board.CreateColumnRequest
	(*ColumnResponse)(nil),         // 11: board.ColumnResponse
	(*DeleteColumnRequest)(nil),    // 12: board.DeleteColumnRequest
	(*UpdateColumnRequest)(nil),    // 13: board.UpdateColumnRequest
	(*CreateTaskRequest)(nil),      // 14: board.CreateTaskRequest
	(*TaskResponse)(nil),           // 15: board.TaskResponse
	(*MoveTaskRequest)(nil),        // 16: board.MoveTaskRequest
	(*MoveTaskResponse)(nil),       // 17: board.MoveTaskResponse
	(*UpdateTaskRequest)(nil),      // 18: board.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),      // 19: board.DeleteTaskRequest
	(*wrapperspb.StringValue)(nil), // 20: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 21: google.protobuf.Empty
}
var file_api_proto_board_proto_depIdxs = []int32{
	4,  // 0: board.ColumnInfo.tasks:type_name -> board.TaskInfo
	5,  // 1: board.BoardInfo.columns:type_name -> board.ColumnInfo
	6,  // 2: board.GetBoardInfoResponse.board:type_name -> board.BoardInfo
	20, // 3: board.UpdateBoardRequest.name:type_name -> google.protobuf.StringValue
	20, // 4: board.UpdateBoardRequest.description:type_name -> google.protobuf.StringValue
	20, // 5: board.UpdateBoardRequest.category:type_name -> google.protobuf.StringValue
	20, // 6: board.UpdateColumnRequest.name:type_name -> google.protobuf.StringValue
	20, // 7: board.UpdateTaskRequest.name:type_name -> google.protobuf.StringValue
	20, // 8: board.UpdateTaskRequest.description:type_name -> google.protobuf.StringValue
	0,  // 9: board.BoardService.CreateBoard:input_type -> board.CreateBoardRequest
	2,  // 10: board.BoardService.GetBoards:input_type -> board.GetBoardsRequest
	3,  // 11: board.BoardService.GetBoardInfo:input_type -> board.GetBoardInfoRequest
	8,  // 12: board.BoardService.UpdateBoard:input_type -> board.UpdateBoardRequest
	9,  // 13: board.BoardService.DeleteBoard:input_type -> board.DeleteBoardRequest
	10, // 14: board.BoardService.CreateColumn:input_type -> board.CreateColumnRequest
	13, // 15: board.BoardService.UpdateColumn:input_type -> board.UpdateColumnRequest
	12, // 16: board.BoardService.DeleteColumn:input_type -> board.DeleteColumnRequest
	14, // 17: board.BoardService.CreateTask:input_type -> board.CreateTaskRequest
	16, // 18: board.BoardService.MoveTask:input_type -> board.MoveTaskRequest
	18, // 19: board.BoardService.UpdateTask:input_type -> board.UpdateTaskRequest
	19, // 20: board.BoardService.DeleteTask:input_type -> board.DeleteTaskRequest
	1,  // 21: board.BoardService.CreateBoard:output_type -> board.BoardResponse
	1,  // 22: board.BoardService.GetBoards:output_type -> board.BoardResponse
	7,  // 23: board.BoardService.GetBoardInfo:output_type -> board.GetBoardInfoResponse
	1,  // 24: board.BoardService.UpdateBoard:output_type -> board.BoardResponse
	21, // 25: board.BoardService.DeleteBoard:output_type -> google.protobuf.Empty
	11, // 26: board.BoardService.CreateColumn:output_type -> board.ColumnResponse
	11, // 27: board.BoardService.UpdateColumn:output_type -> board.ColumnResponse
	21, // 28: board.BoardService.DeleteColumn:output_type -> google.protobuf.Empty
	15, // 29: board.BoardService.CreateTask:output_type -> board.TaskResponse
	17, // 30: board.BoardService.MoveTask:output_type -> board.MoveTaskResponse
	15, // 31: board.BoardService.UpdateTask:output_type -> board.TaskResponse
	21, // 32: board.BoardService.DeleteTask:output_type -> google.protobuf.Empty
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_board_proto_init() }
func file_api_proto_board_proto_init() {
	if File_api_proto_board_proto != nil {
		return
	}
	file_api_proto_board_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_board_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_board_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_board_proto_rawDesc), len(file_api_proto_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_board_proto_goTypes,
		DependencyIndexes: file_api_proto_board_proto_depIdxs,
		MessageInfos:      file_api_proto_board_proto_msgTypes,
	}.Build()
	File_api_proto_board_proto = out.File
	file_api_proto_board_proto_goTypes = nil
	file_api_proto_board_proto_depIdxs = nil
}
